version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns: ["*"]
        exclude-patterns:
          - "typescript"
          - "@types/node"
          - "@types/vscode"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: ["*"]
